language: rust

os:
  - linux

addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    # - os: osx
    #   rust: nightly
    #   env: TARGET=x86_64-apple-darwin
    # - os: osx
    #   rust: beta
    #   env: TARGET=x86_64-apple-darwin
    # - os: osx
    #   rust: stable
    #   env: TARGET=x86_64-apple-darwin

before_script:
  - rustup target add $TARGET
  - cargo install --force cargo-audit
  - rustup component add clippy

script:
  - cargo build --target $TARGET --release
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --target $TARGET
  - cargo audit

before_deploy:
  - mv target/$TARGET/release/gitkv target/$TARGET/release/gitkv-$TARGET

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fvMOLUfi9KoEudSyv2LtwgYP7bh+f1nelj/TeIjteP+u1Omz1p9pP6nIDCrie5tFtY3q4Jor+R7IZoffe/G6KAc7sI4Ndhmr8uB+S9US4gmRI98VMFdGGtjoZzro8Kdrg8+9R0exBgNXJW+ubduSsM0CzKq6HPxmd3TSKRt+2G5vLA5btMbLeeLc8xpmlGrEw2nCjUbEcPislGnQ54wrbrLb+u5SzjPD2G7v8dk1tksfgtcISMylb/aQ+UGrCmMHZfDhAZaooLzxRF+aBtXtku+BFWGjubGa4H/Fj0asKgRic4OzGCi9XwVoBYUgKyb3J7tyO+DtKihBooPytgNcN6zMhqGgxPI6sIFijGatoUZMGKN/J42fpj2f719riaGGuQOcjXbLENl3GfooO97E7mf84SpozhkjYEHEyLRMZTJVk66mCBcrAd6gIa2hdOB3l4Mxy1MzfmDbWwDDHsVflr7fBW8QaWdazziIR12N3iyC7cQdH2lc13l8/N5ffbeTzjWGscZjQWBRECTXjuDklQ9gmG3qlUCdKKsDqMaiuTl21Pi9uqeuebgZS2aVf+y40mdzKd3k89IBUEdMKrvqCvpCV16hm1rlxMtJaVxd9C6gjjrn3hkCWSUXIYzDrLXqwMNSZm02qIu6VEjTyy7rbCcr7fZgti+PbeP43MPvq9s=
  file: target/$TARGET/release/gitkv-$TARGET
  on:
    rust: stable
    tags: true
    branch:
      - /^v\d+\.\d+\.\d+.*$/

cache: cargo
