[package]
name = "handlers"
version = "0.1.0"
authors = ["Intent HQ <engineering@intenthq.com>"]
edition = "2018"
license = "MIT"

[dependencies]
git = { path = "../git" }
actix = "^0.7.9"

# When building for musl (ie. a static binary), we opt into the "vendored"
# feature flag of openssl-sys which compiles libopenssl statically for us.
[target.'cfg(target_env="musl")'.dependencies.openssl-sys]
features = ["vendored"]
version = "*"
